// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	auth "github.com/thienly/todo_service_new/cli/internal/auth"
)

// TokenGetter is an autogenerated mock type for the TokenGetter type
type TokenGetter struct {
	mock.Mock
}

// Get provides a mock function with given fields: username, password
func (_m *TokenGetter) Get(username string, password string) (auth.TokenResponse, error) {
	ret := _m.Called(username, password)

	var r0 auth.TokenResponse
	if rf, ok := ret.Get(0).(func(string, string) auth.TokenResponse); ok {
		r0 = rf(username, password)
	} else {
		r0 = ret.Get(0).(auth.TokenResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
